// Generated by gencpp from file swarm_center/mCPPReqResponse.msg
// DO NOT EDIT!


#ifndef SWARM_CENTER_MESSAGE_MCPPREQRESPONSE_H
#define SWARM_CENTER_MESSAGE_MCPPREQRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace swarm_center
{
template <class ContainerAllocator>
struct mCPPReqResponse_
{
  typedef mCPPReqResponse_<ContainerAllocator> Type;

  mCPPReqResponse_()
    : b(false)  {
    }
  mCPPReqResponse_(const ContainerAllocator& _alloc)
    : b(false)  {
  (void)_alloc;
    }



   typedef uint8_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::swarm_center::mCPPReqResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swarm_center::mCPPReqResponse_<ContainerAllocator> const> ConstPtr;

}; // struct mCPPReqResponse_

typedef ::swarm_center::mCPPReqResponse_<std::allocator<void> > mCPPReqResponse;

typedef boost::shared_ptr< ::swarm_center::mCPPReqResponse > mCPPReqResponsePtr;
typedef boost::shared_ptr< ::swarm_center::mCPPReqResponse const> mCPPReqResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swarm_center::mCPPReqResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swarm_center::mCPPReqResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace swarm_center

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::swarm_center::mCPPReqResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_center::mCPPReqResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarm_center::mCPPReqResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarm_center::mCPPReqResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_center::mCPPReqResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_center::mCPPReqResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swarm_center::mCPPReqResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "88c93a4e354c9b18b18fde29f72f94c2";
  }

  static const char* value(const ::swarm_center::mCPPReqResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x88c93a4e354c9b18ULL;
  static const uint64_t static_value2 = 0xb18fde29f72f94c2ULL;
};

template<class ContainerAllocator>
struct DataType< ::swarm_center::mCPPReqResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swarm_center/mCPPReqResponse";
  }

  static const char* value(const ::swarm_center::mCPPReqResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swarm_center::mCPPReqResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool b\n\
\n\
";
  }

  static const char* value(const ::swarm_center::mCPPReqResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swarm_center::mCPPReqResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mCPPReqResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swarm_center::mCPPReqResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swarm_center::mCPPReqResponse_<ContainerAllocator>& v)
  {
    s << indent << "b: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWARM_CENTER_MESSAGE_MCPPREQRESPONSE_H
