// Generated by gencpp from file swarm_center/mCPPReq.msg
// DO NOT EDIT!


#ifndef SWARM_CENTER_MESSAGE_MCPPREQ_H
#define SWARM_CENTER_MESSAGE_MCPPREQ_H

#include <ros/service_traits.h>


#include <swarm_center/mCPPReqRequest.h>
#include <swarm_center/mCPPReqResponse.h>


namespace swarm_center
{

struct mCPPReq
{

typedef mCPPReqRequest Request;
typedef mCPPReqResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct mCPPReq
} // namespace swarm_center


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::swarm_center::mCPPReq > {
  static const char* value()
  {
    return "81f01bfd9a951b1adf9102125874ff5b";
  }

  static const char* value(const ::swarm_center::mCPPReq&) { return value(); }
};

template<>
struct DataType< ::swarm_center::mCPPReq > {
  static const char* value()
  {
    return "swarm_center/mCPPReq";
  }

  static const char* value(const ::swarm_center::mCPPReq&) { return value(); }
};


// service_traits::MD5Sum< ::swarm_center::mCPPReqRequest> should match 
// service_traits::MD5Sum< ::swarm_center::mCPPReq > 
template<>
struct MD5Sum< ::swarm_center::mCPPReqRequest>
{
  static const char* value()
  {
    return MD5Sum< ::swarm_center::mCPPReq >::value();
  }
  static const char* value(const ::swarm_center::mCPPReqRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::swarm_center::mCPPReqRequest> should match 
// service_traits::DataType< ::swarm_center::mCPPReq > 
template<>
struct DataType< ::swarm_center::mCPPReqRequest>
{
  static const char* value()
  {
    return DataType< ::swarm_center::mCPPReq >::value();
  }
  static const char* value(const ::swarm_center::mCPPReqRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::swarm_center::mCPPReqResponse> should match 
// service_traits::MD5Sum< ::swarm_center::mCPPReq > 
template<>
struct MD5Sum< ::swarm_center::mCPPReqResponse>
{
  static const char* value()
  {
    return MD5Sum< ::swarm_center::mCPPReq >::value();
  }
  static const char* value(const ::swarm_center::mCPPReqResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::swarm_center::mCPPReqResponse> should match 
// service_traits::DataType< ::swarm_center::mCPPReq > 
template<>
struct DataType< ::swarm_center::mCPPReqResponse>
{
  static const char* value()
  {
    return DataType< ::swarm_center::mCPPReq >::value();
  }
  static const char* value(const ::swarm_center::mCPPReqResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SWARM_CENTER_MESSAGE_MCPPREQ_H
